# Generated by Django 4.2.7 on 2023-11-27 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apps_user", "0002_user_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("tax_number", models.CharField(verbose_name=50)),
                ("po_number", models.CharField(verbose_name=5)),
                ("vat_id", models.CharField(verbose_name=50)),
                ("bank_name", models.CharField(verbose_name=200)),
                ("iban", models.CharField(verbose_name=200)),
                ("swift_bic", models.CharField(verbose_name=200)),
                ("first_name", models.CharField(verbose_name=50)),
                ("last_name", models.CharField(verbose_name=50)),
                ("transfer_deadline_day", models.PositiveSmallIntegerField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
