# Generated by Django 4.2.7 on 2023-11-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_user", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bank_name",
            field=models.CharField(blank=True, null=True, verbose_name=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, null=True, verbose_name=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="iban",
            field=models.CharField(blank=True, null=True, verbose_name=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, null=True, verbose_name=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="po_number",
            field=models.CharField(blank=True, null=True, verbose_name=5),
        ),
        migrations.AlterField(
            model_name="profile",
            name="swift_bic",
            field=models.CharField(blank=True, null=True, verbose_name=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="tax_number",
            field=models.CharField(blank=True, null=True, verbose_name=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="transfer_deadline_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="vat_id",
            field=models.CharField(blank=True, null=True, verbose_name=50),
        ),
    ]
