# Generated by Django 4.2.7 on 2023-11-27 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("apps_user", "0004_alter_profile_bank_name_alter_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
