# Generated by Django 4.2.7 on 2023-12-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_user", "0010_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rate_per_ue",
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="ue_hours",
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name="profile",
            name="vat_cost",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
