# Generated by Django 4.2.7 on 2023-12-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_user", "0011_profile_rate_per_ue_profile_ue_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="class_room",
            field=models.CharField(default="", verbose_name=10),
        ),
    ]
