# Generated by Django 4.2.7 on 2023-11-29 10:52

import apps.invoice.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_invoice", "0002_alter_invoice_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_xls",
            field=models.FileField(
                max_length=50,
                upload_to="",
                validators=[apps.invoice.validators.validate_file_extension],
            ),
        ),
    ]
